### PR TITLE
Added exception DisabledSwitch

### PR DESCRIPTION
**Pull request by Alopalao**
Initially based on Issue #317 

### Summary

Added exception `DisabledSwitch` to detect when an EVC has a disabled switch in its path

### Local tests
Added unit tests
Tried to create EVC with disabled switches

### CODE REVIEW

**Comment by Alopalao** [comment]
Inter-switch EVC can still be created if the disabled switch is in the path. Wanted to confirm something first:
- what are the cases where `pathfinder` does not include a switch in the path?

**Review by viniarck — COMMENTED** [review]
@Alopalao it's evolving well, however, I'll recommend that instead of just checking for `not switch.is_enabled()` you check for `switch.status != EntityStatus.UP`, just so it also covers when a switch.status is `DOWN` (and maybe the exception could be `SwitchStatusNotUp` or something else along these lines?), and that way it's also easier to refactor later when @Ktmi might need to replace or augment some conditionals checking with the future `status_reason` that will be introduced. Wdyt?

**Comment by viniarck** [comment]
> Inter-switch EVC can still be created if the disabled switch is in the path. Wanted to confirm something first:
> 
> * what are the cases where `pathfinder` does not include a switch in the path?

Switch, Interface, and Link whose statuses are [`UP` are part of the current graph](https://github.com/kytos-ng/pathfinder/blob/master/graph.py#L50-L73), anything else won't be found.

**Comment by Alopalao** [comment]
> I'll recommend that instead of just checking for `not switch.is_enabled()` you check for `switch.status != EntityStatus.UP`

Change it to `switch.status != **EntityStatus.DISABLED`, it reflects better the required change. More in issue #332

**Comment by viniarck** [comment]
@Alopalao you can close this PR since https://github.com/kytos-ng/mef_eline/pull/336 has landed.

**Pull request closed without merging**
