### PR TITLE
Made changes for vue3sfcloader compatibility k-toolbar

### LINKED ISSUE #520: k-toolbar form tags are misplaced
The form tags `<form> </form>` are placed incorrectly within the html section of the `k-toolbar`.
image

### LINKED ISSUE #539: Modifications for vue3-sfc-loader compatibility
Mef_eline UI needs to be modified to be compatible with the vue3-sfc-loader.

### PR DESCRIPTION
**Pull request by HeriLFIU**
Closes #539 
Closes #520

### Summary

These changes are made to that mef_eline k-toolbar can be loaded in by the vue3-sfc-loader.
The try and catch block would not function within the html it needed to be within its own method.
There were also some undefined variables.

Mef_eline also had an issue with its form tags, since they were incorrectly placed. They were placed inside of a k-accordion-item while still spanning multiple other outside elements. Because of this I placed it inside the single k-accordion-item.

### CODE REVIEW

**Comment by HeriLFIU** [comment]
@viniarck I accidentally enabled a vue3 formatter in my VSCode plugins, should I disable it?

**Comment by HeriLFIU** [comment]
I noticed now while making the pull request, but I don't know if I should keep the formatted code.

**Comment by viniarck** [comment]
> I noticed now while making the pull request, but I don't know if I should keep the formatted code.

@HeriLFIU, I missed the other prior notification.

Although the intention is great. I'd recommend avoid reformatting the code in this PR. In the future we can officialize a formatter and stick to it, but other than that for now it can create too much extra diffs, although not too difficult to follow but yes, it's more things to review and check for, so let's minimize that too for now, OK?

**Comment by HeriLFIU** [comment]
@viniarck just removed the formatting. It should be good to go.

**Comment by viniarck** [comment]
> @viniarck just removed the formatting. It should be good to go.

Great. Let's ship it, Heriberto.

**Review by viniarck — APPROVED** [review]
@HeriLFIU, looks good. Before this get merged though. Can you check the `</form>` tag fix you mentioned if you included as you mentioned in the description?

**Comment by HeriLFIU** [comment]
@viniarck yes, thank you, I forgot to add it again after removing the formatting. Should be good now.

**Pull request merged**
