### PR TITLE
[fix] update `primary_path` or `backup_path` empty

### LINKED ISSUE #230: Patch EVC to remove primary_path or backup_path
Hello,

What should be the payload when patching an EVC to allow removing primary_path or backup_path? I've tested with an Empty list and also a None value, and both failed.

I've also tested not specifying the attribute, which also failed.

This maybe related to issue #41.

### PR DESCRIPTION
**Pull request by viniarck**
Closes #230 

This PR is on top of PR #232 

### Summary

- See changelog file

### Local Tests

I also explored locally based on some cases that @italovalcy [highlighted](https://github.com/kytos-ng/mef_eline/issues/230#issuecomment-1358261774):

1 - With a ring topology, I created an EVC non dynamic path with `primary_path` between s1 and s3:

```
{
    "name": "epl",
    "dynamic_backup_path": false,
    "uni_a": {
        "interface_id": "00:00:00:00:00:00:00:01:1"
    },
    "uni_z": {
        "interface_id": "00:00:00:00:00:00:00:03:1"
    },
    "primary_path": [
        {
            "endpoint_a": {
                "id": "00:00:00:00:00:00:00:01:4"
            },
            "endpoint_b": {
                "id": "00:00:00:00:00:00:00:03:3"
            }
        }
    ]
}
```

1.1 - I tried to set an empty `primary_path`, since `dynamic_backup_path` is `false` by default it resulted in 400:

```
{
    "primary_path": []
}
```

```
{
    "code": 400,
    "description": "The EVC must have a primary path or allow dynamic paths.",
    "name": "Bad Request"
}
```

1.2 - Then I set an empty `primary_path` but this time with `dynamic_backup_path: true`, simulating a case where the network operator no longer wants to use a static `primary_path`.

```
{
    "dynamic_backup_path": true,
    "primary_path": []
}
```

```
{
    "12a724a1f5914e": {
        "active": true,
        "archived": false,
        "backup_links": [],
        "backup_path": [],
        "bandwidth": 0,
        "circuit_scheduler": [],
        "creation_time": "2022-12-20T17:42:13",
        "current_path": [
            {
                "active": true,
                "enabled": true,
                "endpoint_a": {
                    "active": true,
                    "enabled": true,
                    "id": "00:00:00:00:00:00:00:01:4",
                    "link": "c8b55359990f89a5849813dc348d30e9e1f991bad1dcb7f82112bd35429d9b07",
                    "lldp": true,
                    "mac": "56:51:f6:ea:07:e0",
                    "metadata": {},
                    "name": "s1-eth4",
                    "nni": true,
                    "port_number": 4,
                    "speed": 1250000000.0,
                    "switch": "00:00:00:00:00:00:00:01",
                    "type": "interface",
                    "uni": false
                },
                "endpoint_b": {
                    "active": true,
                    "enabled": true,
                    "id": "00:00:00:00:00:00:00:03:3",
                    "link": "c8b55359990f89a5849813dc348d30e9e1f991bad1dcb7f82112bd35429d9b07",
                    "lldp": true,
                    "mac": "e2:f8:58:62:dc:29",
                    "metadata": {},
                    "name": "s3-eth3",
                    "nni": true,
                    "port_number": 3,
                    "speed": 1250000000.0,
                    "switch": "00:00:00:00:00:00:00:03",
                    "type": "interface",
                    "uni": false
                },
                "id": "c8b55359990f89a5849813dc348d30e9e1f991bad1dcb7f82112bd35429d9b07",
                "metadata": {
                    "s_vlan": {
                        "tag_type": 1,
                        "value": 3
                    }
                }
            }
        ],
        "dynamic_backup_path": true,
        "enabled": true,
        "end_date": null,
        "failover_path": [],
        "id": "12a724a1f5914e",
        "metadata": {},
        "name": "epl",
        "owner": null,
        "primary_constraints": {},
        "primary_links": [],
        "primary_path": [],
        "queue_id": null,
        "request_time": "2022-12-20T17:42:13",
        "sb_priority": null,
        "secondary_constraints": {},
        "service_level": 0,
        "start_date": "2022-12-20T17:42:13",
        "uni_a": {
            "interface_id": "00:00:00:00:00:00:00:01:1",
            "tag": null
        },
        "uni_z": {
            "interface_id": "00:00:00:00:00:00:00:03:1",
            "tag": null
        }
    }
}
```

2 - Finally I created an EPL intra-switch with `primary_path` empty:

```
{
    "name": "epl",
    "service_level": 7,
    "primary_path": [],
    "uni_a": {
        "interface_id": "00:00:00:00:00:00:00:01:1"
    },
    "uni_z": {
       "interface_id": "00:00:00:00:00:00:00:01:2"
    }
}
```

```
{
    "active": true,
    "archived": false,
    "backup_links": [],
    "backup_path": [],
    "bandwidth": 0,
    "circuit_scheduler": [],
    "creation_time": "2022-12-20T17:47:39",
    "current_path": [],
    "dynamic_backup_path": false,
    "enabled": true,
    "end_date": null,
    "failover_path": [],
    "id": "623b9c7ea8244e",
    "metadata": {},
    "name": "epl",
    "owner": null,
    "primary_constraints": {
        "spf_attribute": "hop"
    },
    "primary_links": [],
    "primary_path": [],
    "queue_id": null,
    "request_time": "2022-12-20T17:47:39",
    "sb_priority": null,
    "secondary_constraints": {
        "spf_attribute": "hop"
    },
    "service_level": 7,
    "start_date": "2022-12-20T17:47:39",
    "uni_a": {
        "interface_id": "00:00:00:00:00:00:00:01:1"
    },
    "uni_z": {
        "interface_id": "00:00:00:00:00:00:00:01:2"
    }
}
```

### CODE REVIEW

**Comment by viniarck** [comment]
I'll also dispatch an e2e test CI execution with this branch. 

FYI, related issue regarding validations in general on this endpoint `PATCH /evc/<circuit_id>` https://github.com/kytos-ng/mef_eline/issues/194 that aren't covered yet

**Review by italovalcy — APPROVED** [review]
LGTM! Excellent to have this fixed, @viniarck

**Comment by viniarck** [comment]
> LGTM! Excellent to have this fixed, @viniarck

Thanks for reviewing @italovalcy, FYI, there was one e2e test failure, but [I've sent a PR for it too](https://github.com/amlight/kytos-end-to-end-tests/pull/194), so before merging this one, to avoid having e2e nighly exec failures these two PRs should land in the same day:

```
tests/test_e2e_10_mef_eline.py::TestE2EMefEline::test_125_patch_dynamic_backup_path: 2022-12-20,18:58:03.246763 - 2022-12-20,18:58:13.956150
=========================== rerun test summary info ============================
RERUN tests/test_e2e_10_mef_eline.py::TestE2EMefEline::test_125_patch_dynamic_backup_path
RERUN tests/test_e2e_10_mef_eline.py::TestE2EMefEline::test_125_patch_dynamic_backup_path
=========================== short test summary info ============================
FAILED tests/test_e2e_10_mef_eline.py::TestE2EMefEline::test_125_patch_dynamic_backup_path - assert True == False
= 1 failed, 171 passed, 2 skipped, 18 xfailed, 7 xpassed, 793 warnings, 2 rerun in 10370.73s (2:52:50) =
```

**Comment by viniarck** [comment]
https://github.com/amlight/kytos-end-to-end-tests/pull/194 has landed

**Pull request merged**
