### PR TITLE
Solved errors with pipeline installation process

### PR DESCRIPTION
**Pull request by Alopalao**
### Summary

Solving some issues with the installation of a pipeline.

### Local Tests
Installing pipelines with a table ID different than 0

### CODE REVIEW

**Review by viniarck — COMMENTED** [review]
@Alopalao, can you elaborate more on which error is this fixing? 

The changes look like it's just a refactoring, which seems ok as well, did you mean to also push extra commits or is that all? It's OK not to have an issue associated sometimes when it's just a simple refactoring, but if it's an actual issue being fixed we should have an issue associated with it.

**Comment by Alopalao** [comment]
> @Alopalao, can you elaborate more on which error is this fixing?

I tried to reproduce it but now it is gone. I am going to keep an eye for it.

**Comment by viniarck** [comment]
> > @Alopalao, can you elaborate more on which error is this fixing?
> 
> I tried to reproduce it but now it is gone. I am going to keep an eye for it.

OK. In the meantime, please let's leave this PR as a draft then just so it does't show up in the review filters.

**Comment by viniarck** [comment]
Closing this PR since it wasn't semantically fixing anything and no new updates were raised. If anything else changes you can open a new PR.

**Pull request closed without merging**
